data_dir: /Users/hanna/mldl_project-1/kaggle-child-mind-institute-detect-sleep-states/data
processed_dir: /Users/hanna/mldl_project-1/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: /Users/hanna/mldl_project-1/kaggle-child-mind-institute-detect-sleep-states/output
model_dir: /Users/hanna/mldl_project-1/kaggle-child-mind-institute-detect-sleep-states/output/train
sub_dir: ./